select
FBillNo as "单据编号",
FEntryID as "单据分录号",
Fauxqty as "实收数量",
FAuxQtyMust as "应收数量",
FBatchNo as "批号",
Fdate as "日期",
FDCSPID as "仓位",
FDCStockID as "收货仓库",
FDeptID as "交货单位",
FItemID as "产品名称",
FKFDate as "生产/采购日期",
FKFPeriod as "保质期(天)",
Fmodel as "规格型号",
FNumber as "产品长代码",
FQty as "基本单位实收数量",
FQtyMust as "基本单位应收数量",
FSourceBillNo as "源单单号",
FSourceTranType as "源单类型",
FVchInterID as "凭证号"
from dbo.vwICBill_2;
