CREATE TABLE [dbo].[SEOrder] (
                                 [FBrNo] varchar(10) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                 [FInterID] int  NOT NULL,
                                 [FBillNo] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                 [FCurrencyID] int  NULL,
                                 [FCustID] int  NULL,
                                 [FDate] datetime  NULL,
                                 [FPayStyle] varchar(30) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FPayDate] datetime  NULL,
                                 [FFetchStyle] varchar(30) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FFetchDate] datetime  NULL,
                                 [FFetchAdd] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FSaleStyle] int  NULL,
                                 [FDeptID] int  NULL,
                                 [FEmpID] int  NULL,
                                 [FCheckerID] int  NULL,
                                 [FBillerID] int  NULL,
                                 [FNote] varchar(30) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FClosed] smallint  NOT NULL,
                                 [FTranType] int  NOT NULL,
                                 [FInvoiceClosed] smallint  NULL,
                                 [FBClosed] smallint  NOT NULL,
                                 [FMangerID] int  NULL,
                                 [FSettleID] int  NULL,
                                 [FExchangeRate] float(53)  NULL,
                                 [FDiscountType] bit  NOT NULL,
                                 [FStatus] smallint  NOT NULL,
                                 [FCancellation] bit  NOT NULL,
                                 [FMultiCheckLevel1] int  NULL,
                                 [FMultiCheckLevel2] int  NULL,
                                 [FMultiCheckLevel3] int  NULL,
                                 [FMultiCheckLevel4] int  NULL,
                                 [FMultiCheckLevel5] int  NULL,
                                 [FMultiCheckLevel6] int  NULL,
                                 [FMultiCheckDate1] datetime  NULL,
                                 [FMultiCheckDate2] datetime  NULL,
                                 [FMultiCheckDate3] datetime  NULL,
                                 [FMultiCheckDate4] datetime  NULL,
                                 [FMultiCheckDate5] datetime  NULL,
                                 [FMultiCheckDate6] datetime  NULL,
                                 [FCurCheckLevel] int  NULL,
                                 [FTransitAheadTime] real  NULL,
                                 [FPOOrdBillNo] nvarchar(510) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FRelateBrID] int  NULL,
                                 [FImport] int  NOT NULL,
                                 [FOrderAffirm] int  NULL,
                                 [FTranStatus] int  NULL,
                                 [FUUID] uniqueidentifier  NOT NULL ROWGUIDCOL,
                                 [FSystemType] int  NOT NULL,
                                 [FCashDiscount] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                 [FCheckDate] datetime  NULL,
                                 [FExplanation] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                 [FSettleDate] datetime  NULL,
                                 [FSelTranType] int  NOT NULL,
                                 [FChildren] int  NOT NULL,
                                 [FBrID] int  NULL,
                                 [FAreaPS] int  NOT NULL,
                                 [FClassTypeID] int  NOT NULL,
                                 [FManageType] int  NULL,
                                 [FSysStatus] smallint  NOT NULL,
                                 [FVersionNo] nvarchar(20) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                 [FChangeDate] datetime  NULL,
                                 [FChangeCauses] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FChangeMark] int  NOT NULL,
                                 [FChangeUser] int  NOT NULL,
                                 [FValidaterName] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FConsignee] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FDrpRelateTranType] int  NOT NULL,
                                 [FPrintCount] smallint  NOT NULL,
                                 [FExchangeRateType] int  NOT NULL,
                                 [FCustAddress] int  NOT NULL,
                                 [FPlanCategory] int  NOT NULL,
                                 [FHeadSelfS0152] int  NULL,
                                 [FHeadSelfS0153] int  NULL,
                                 [FHeadSelfS0154] int  NULL,
                                 [FHeadSelfS0155] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FHeadSelfS0159] int  NULL,
                                 [FMultiCheckStatus] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                 [FHeadSelfS0160] varchar(1000) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FHeadSelfS0161] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FHeadSelfS0162] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                 [FHeadSelfS0163] int  NULL,
                                 [FOperDate] varchar(255)  NOT NULL,
                                 [FHeadSelfS0164] int  NULL,
                                 [FHeadSelfS0165] int  NULL,
                                 [FHeadSelfS0166] int  NULL,
                                 [FHeadSelfS0167] int  NULL,
                                 [FHeadSelfS0168] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL
)
    ON [PRIMARY]
GO