CREATE TABLE [dbo].[FDSC] (
                              [PrjKey] varchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                              [CDID] varchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                              [PrjState] int DEFAULT (0) NOT NULL,
                              [EvalResult] int DEFAULT (0) NULL,
                              [RKey] int DEFAULT NULL NULL,
                              [cdmc] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [operator_name] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [dylx] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [dcxh] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [dcmc] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [scrq] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [scdw] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [dcph] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [sbmc] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [qyrq] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [jchj] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [fzdz] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [zzdy] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [fdlx] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [fdfs] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [jljg] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [bzsj] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [jstj] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [dlcs] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [hfsj] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [fdrq] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [jsrq] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [fdkssj] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [fdjssj] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [xxxqs] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [fdts] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [dzys] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [yfws] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt1] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt2] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt3] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt4] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt5] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt6] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt7] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt255] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt9] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt10] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [volt11] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [dch] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [bz] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir1] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir2] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir3] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir4] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir5] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir6] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir7] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir255] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [shortcir9] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity1] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity2] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity3] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity4] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity5] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity6] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity7] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity8] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [capacity9] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [mark] int DEFAULT NULL NULL,
                              [recordnum] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [Comfirmer] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [Evaluater] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [Deleter] varchar(255) COLLATE Chinese_PRC_CI_AS DEFAULT NULL NULL,
                              [jyl] float(53) DEFAULT NULL NULL
)
    ON [PRIMARY]
GO

ALTER TABLE [dbo].[FDSC] SET (LOCK_ESCALATION = TABLE)