-- 放电项目表 HubDischargeProject
select PrjKey,
       CDID,
       PrjState,
       EvalResult,
       RKey,
       cdmc,
       operator_name,
       dylx,
       dcxh,
       dcmc,
       scrq,
       scdw,
       dcph,
       sbmc,
       qyrq,
       jchj,
       fzdz,
       zzdy,
       fdlx,
       fdfs,
       jljg,
       bzsj,
       jstj,
       dlcs,
       hfsj,
       fdrq,
       jsrq,
       fdkssj,
       fdjssj,
       xxxqs,
       fdts,
       dzys,
       yfws,
       volt1,
       volt2,
       volt3,
       volt4,
       volt5,
       volt6,
       volt7,
       volt8,
       volt9,
       volt10,
       volt11,
       dch,
       bz,
       shortcir1,
       shortcir2,
       shortcir3,
       shortcir4,
       shortcir5,
       shortcir6,
       shortcir7,
       shortcir8,
       shortcir9,
       capacity1,
       capacity2,
       capacity3,
       capacity4,
       capacity5,
       capacity6,
       capacity7,
       capacity8,
       capacity9,
       mark,
       recordnum,
       Comfirmer,
       ComfirmTime,
       Evaluater,
       EvaluateTime,
       Deleter,
       DelTime,
       InTime,
       jyl
from rqmdb.fd_cs;




-- 开压开压 HubDischargeEvolt
select fe.PrjKey,
       fe.CDID,
       fe.daynum,
       fe.dy_dm,
       fe.dy,
       fe.volt1,
       fe.volt2,
       fe.volt3,
       fe.volt4,
       fe.volt5,
       fe.volt6,
       fe.volt7,
       fe.volt8,
       fe.volt9,
       fe.daytime,
       fe.cdmc,
       fc.InTime
from fd_evolt fe
    inner join fd_cs fc on fe.PrjKey = fc.PrjKey
;