select FbillNo         as "编号",
       Fauxprice       as "单价",
       Fauxqty         as "数量",
       FBatchNo        as "批号",
       FcuQty          as "常用单位数量",
       FCUUnitID       as "常用单位",
       Fdate           as "日期",
       FNumber         as "产品长代码",
       FItemID         as "产品名称",
       FKFDate         as "生产/采购日期",
       FMapName        as "对应名称",
       FMapNumber      as "对应代码",
       FQty            as "基本单位数量",
       FRelateBrID     as "订货机构",
       FSaleStyle      as "销售方式",
       FShortNumber    as "产品代码",
       FSManagerID     as "保管",
       FSourceBillNo   as "源单单号",
       FSourceTranType as "源单类型"
from dbo.vwICBill_8;
