CREATE TABLE [dbo].[Client] (
                                        [FItemID] int  NOT NULL,
                                        [FAddress] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FCity] varchar(80) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FProvince] varchar(80) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FCountry] varchar(80) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FPostalCode] varchar(20) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FPhone] varchar(40) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FFax] varchar(40) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FEmail] varchar(40) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FHomePage] varchar(80) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FCreditLimit] varchar(20) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FTaxID] varchar(40) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FBank] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FAccount] varchar(80) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FBankNumber] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FBrNo] varchar(10) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FBoundAttr] int  NULL,
                                        [FErpClsID] int  NULL,
                                        [FShortName] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FPriorityID] int  NULL,
                                        [FPOGroupID] int  NULL,
                                        [FStatus] int  NULL,
                                        [FLanguageID] int  NULL,
                                        [FRegionID] int  NULL,
                                        [FTrade] int  NULL,
                                        [FMinPOValue] float(53)  NULL,
                                        [FMaxDebitDate] float(53)  NULL,
                                        [FLegalPerson] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FContact] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FContactAcct] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FPhoneAcct] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FFaxAcct] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FZipAcct] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FEmailAcct] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FAddrAcct] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FTax] real  NULL,
                                        [FCyID] int  NULL,
                                        [FSetID] int  NULL,
                                        [FSetDLineID] int  NULL,
                                        [FTaxNum] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FPriceClsID] int  NULL,
                                        [FOperID] int  NULL,
                                        [FCIQNumber] varchar(20) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FDeleted] smallint  NOT NULL,
                                        [FSaleMode] int  NOT NULL,
                                        [FName] varchar(80) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FNumber] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FParentID] int  NOT NULL,
                                        [FShortNumber] varchar(80) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FARAccountID] int  NOT NULL,
                                        [FAPAccountID] int  NOT NULL,
                                        [FpreAcctID] int  NOT NULL,
                                        [FlastTradeAmount] money  NOT NULL,
                                        [FlastRPAmount] money  NOT NULL,
                                        [FfavorPolicy] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [Fdepartment] int  NOT NULL,
                                        [Femployee] int  NOT NULL,
                                        [Fcorperate] varchar(80) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FbeginTradeDate] datetime  NULL,
                                        [FendTradeDate] datetime  NULL,
                                        [FlastTradeDate] datetime  NULL,
                                        [FlastReceiveDate] datetime  NULL,
                                        [FcashDiscount] varchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FcurrencyID] int  NOT NULL,
                                        [FmaxDealAmount] float(53)  NOT NULL,
                                        [FminForeReceiveRate] float(53)  NOT NULL,
                                        [FminReserverate] float(53)  NOT NULL,
                                        [FdebtLevel] int  NOT NULL,
                                        [FCarryingAOS] int  NOT NULL,
                                        [FIsCreditMgr] bit  NOT NULL,
                                        [FCreditPeriod] int  NOT NULL,
                                        [FCreditLevel] int  NOT NULL,
                                        [FPayTaxAcctID] int  NOT NULL,
                                        [FValueAddRate] decimal(28,2)  NULL,
                                        [FTypeID] int  NOT NULL,
                                        [FCreditDays] int  NULL,
                                        [FCreditAmount] decimal(18,2)  NULL,
                                        [FStockIDAssign] int  NOT NULL,
                                        [FStockIDInst] int  NOT NULL,
                                        [FStockIDKeep] int  NULL,
                                        [FPaperPeriod] datetime  NULL,
                                        [FAlarmPeriod] int  NULL,
                                        [FLicAndPermit] bit  NOT NULL,
                                        [FOtherARAcctID] int  NOT NULL,
                                        [FOtherAPAcctID] int  NOT NULL,
                                        [FPreAPAcctID] int  NOT NULL,
                                        [FSaleID] int  NULL,
                                        [FHelpCode] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FModifyTime] varchar(255)  NOT NULL,
                                        [FNameEN] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FAddrEn] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FCIQCode] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FRegion] int  NULL,
                                        [FMobilePhone] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [FPayCondition] int  NULL,
                                        [FManageType] int  NULL,
                                        [FClass] int  NOT NULL,
                                        [FValue] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FRegUserID] int  NOT NULL,
                                        [FLastModifyDate] datetime  NULL,
                                        [FRecentContactDate] datetime  NULL,
                                        [FRegDate] datetime  NULL,
                                        [FFlat] int  NOT NULL,
                                        [FClassTypeID] int  NOT NULL,
                                        [FCoSupplierID] int  NULL,
                                        [FShareStatus] int  NOT NULL,
                                        [FCustType] int  NOT NULL,
                                        [FSuperiorID] int  NOT NULL,
                                        [FClueID] int  NOT NULL,
                                        [FLastMailTime] datetime  NULL,
                                        [FCityID] int  NOT NULL,
                                        [FProvinceID] int  NOT NULL,
                                        [FSex] varchar(5) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FMobile] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FDuty] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FWorkSite] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FWorkUnit] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FIncomeLevel] int  NOT NULL,
                                        [FStratum] int  NOT NULL,
                                        [FAge] int  NOT NULL,
                                        [FBirthday] datetime  NULL,
                                        [FNation] nvarchar(10) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FBizPostCode] varchar(20) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FIM] varchar(20) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [FBizPhone] varchar(40) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                        [F_102] int  NULL,
                                        [F_104] varchar(50) COLLATE Chinese_PRC_CI_AS  NULL,
                                        [F_105] varchar(200) COLLATE Chinese_PRC_CI_AS  NULL
)
    ON [PRIMARY]
GO