select
from SEOrder so
         inner join WorkOrder wo on wo.FOrderInterID=so.FInterID
         inner join PickOrder po on po.FWorkNo=wo.FBillNo
         inner join FlowCard fc on fc.FTaskBillNo=po.FBillNo
         inner join TaskReportCode trc on trc.FCode =fc.FFlowCardNo
         inner join CommissionTest ct on ct.ftext=trc.fbatch
         inner join CommissionTestEntry cte on ct.FID=cte.fid;



SELECT count(*) FROM dbo.test
;

select top 100 * from  WorkOrder wo inner join PickOrder po on po.FWorkNo=wo.FBillNo




select top 100 * from SEOrder so
                          inner join  ICMO wo on wo.FOrderInterID=so.FInterID
                          inner join  MES14.dbo.M_Order po on po.FWorkNo=wo.FBillNo
                          inner join  MES14.dbo.M_FlowCard fc on fc.FTaskBillNo=po.FBillNo
CREATE TABLE [dbo].[OrderEntry] (
                                    [FBrNO] varchar(10) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                    [FInterID] int  NOT NULL,
                                    [FEntryID] int  NOT NULL,
                                    [FItemID] int  NULL,
                                    [FQty] decimal(28,10)  NOT NULL,
                                    [FCommitQty] decimal(28,10)  NOT NULL,
                                    [FPrice] decimal(28,10)  NOT NULL,
                                    [FAmount] decimal(20,2)  NOT NULL,
                                    [FTaxRate] decimal(28,10)  NULL,
                                    [FTaxAmount] decimal(20,2)  NOT NULL,
                                    [FTax] decimal(20,2)  NOT NULL,
                                    [FDiscount] real  NULL,
                                    [FNote] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FDate] datetime  NULL,
                                    [FDiscountAmount] decimal(20,2)  NULL,
                                    [FInvoiceQty] decimal(28,10)  NOT NULL,
                                    [FBCommitQty] decimal(28,10)  NOT NULL,
                                    [FTranLeadTime] int  NOT NULL,
                                    [FATPDeduct] int  NOT NULL,
                                    [FCostObjectID] int  NOT NULL,
                                    [FUnitID] int  NOT NULL,
                                    [FAuxBCommitQty] decimal(28,10)  NOT NULL,
                                    [FAuxCommitQty] decimal(28,10)  NOT NULL,
                                    [FAuxInvoiceQty] decimal(28,10)  NOT NULL,
                                    [FAuxPrice] decimal(28,10)  NOT NULL,
                                    [FAuxQty] decimal(28,10)  NOT NULL,
                                    [FUniDiscount] decimal(28,10)  NOT NULL,
                                    [FFinalAmount] decimal(20,2)  NOT NULL,
                                    [FSourceEntryID] int  NOT NULL,
                                    [FHaveMrp] int  NULL,
                                    [FStockQty] decimal(28,10)  NOT NULL,
                                    [FAuxStockQty] decimal(28,10)  NOT NULL,
                                    [FBatchNo] varchar(200) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                    [FCESS] decimal(20,2)  NOT NULL,
                                    [FAdviceConsignDate] datetime  NULL,
                                    [FBomInterID] int  NOT NULL,
                                    [FMapNumber] varchar(80) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                    [FMapName] nvarchar(256) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FLockFlag] int  NOT NULL,
                                    [FInForeCast] int  NULL,
                                    [FAllAmount] decimal(28,4)  NOT NULL,
                                    [FAllStdAmount] decimal(28,4)  NOT NULL,
                                    [FAuxPropID] int  NOT NULL,
                                    [FAuxPriceDiscount] decimal(28,10)  NOT NULL,
                                    [FPriceDiscount] decimal(28,10)  NOT NULL,
                                    [FQtyInvoice] decimal(28,10)  NOT NULL,
                                    [FQtyInvoiceBase] decimal(28,10)  NOT NULL,
                                    [FTaxAmt] decimal(28,4)  NOT NULL,
                                    [FAuxTaxPrice] decimal(28,10)  NOT NULL,
                                    [FTaxPrice] decimal(28,10)  NOT NULL,
                                    [FReceiveAmountFor_Commit] decimal(28,4)  NOT NULL,
                                    [FReceiveAmount_Commit] decimal(28,4)  NOT NULL,
                                    [FSecCoefficient] decimal(28,10)  NOT NULL,
                                    [FSecQty] decimal(28,10)  NOT NULL,
                                    [FSecCommitQty] decimal(28,10)  NOT NULL,
                                    [FSourceTranType] int  NOT NULL,
                                    [FSourceInterId] int  NOT NULL,
                                    [FSourceBillNo] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                    [FContractInterID] int  NOT NULL,
                                    [FContractEntryID] int  NOT NULL,
                                    [FContractBillNo] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                    [FMRPLockFlag] int  NOT NULL,
                                    [FMRPTrackFlag] int  NOT NULL,
                                    [FOrderCommitQty] decimal(28,13)  NOT NULL,
                                    [FOrderSecCommitQty] decimal(28,13)  NOT NULL,
                                    [FAuxQtyInvoice] decimal(28,10)  NOT NULL,
                                    [FCommitInstall] decimal(28,10)  NOT NULL,
                                    [FAuxCommitInstall] decimal(28,10)  NOT NULL,
                                    [FMrpClosed] int  NOT NULL,
                                    [FAuxInCommitQty] decimal(28,10)  NOT NULL,
                                    [FInCommitQty] decimal(28,10)  NOT NULL,
                                    [FSecInCommitQty] decimal(28,10)  NOT NULL,
                                    [FApplyCommitQty] decimal(28,10)  NOT NULL,
                                    [FAuxApplyCommitQty] decimal(28,10)  NOT NULL,
                                    [FSecApplyCommitQty] decimal(28,10)  NOT NULL,
                                    [FEvaluated] int  NOT NULL,
                                    [FPackUnitID] int  NOT NULL,
                                    [FPackCount] int  NOT NULL,
                                    [FPackType] decimal(28,10)  NOT NULL,
                                    [FDetailID] int  NOT NULL,
                                    [FMapID] int  NOT NULL,
                                    [FGoodsDesc] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                    [FAmountAfterDiscount] decimal(28,4)  NOT NULL,
                                    [FInformCommitQty] decimal(28,10)  NOT NULL,
                                    [FAuxInformCommitQty] decimal(28,10)  NOT NULL,
                                    [FSecInformCommitQty] decimal(28,10)  NOT NULL,
                                    [FPurCommitQty] decimal(28,10)  NOT NULL,
                                    [FAuxPurCommitQty] decimal(28,10)  NOT NULL,
                                    [FSecPurCommitQty] decimal(28,10)  NOT NULL,
                                    [FMrpAutoClosed] int  NULL,
                                    [FSecStockQty] decimal(23,10)  NOT NULL,
                                    [FSecInvoiceQty] decimal(23,10)  NOT NULL,
                                    [FSecCommitInstall] decimal(23,10)  NOT NULL,
                                    [FPlanMode] int  NOT NULL,
                                    [FMTONo] nvarchar(50) COLLATE Chinese_PRC_CI_AS  NOT NULL,
                                    [FOrderBillNo] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FOrderEntryID] int  NULL,
                                    [FDiffQtyClosed] decimal(28,10)  NOT NULL,
                                    [FBOMCategory] int  NOT NULL,
                                    [FOrderBOMStatus] int  NOT NULL,
                                    [FOrderBOMInterID] int  NOT NULL,
                                    [FIsAltered] tinyint  NOT NULL,
                                    [FAmountExceptDisCount] decimal(28,4)  NOT NULL,
                                    [FAllAmountExceptDisCount] decimal(28,4)  NOT NULL,
                                    [FEntryDisCount] decimal(28,4)  NOT NULL,
                                    [FCommitAmt] decimal(23,10)  NULL,
                                    [FCommitAmtTax] decimal(23,10)  NULL,
                                    [FCommitTax] decimal(23,10)  NULL,
                                    [FEntrySelfS0164] int  NULL,
                                    [FEntrySelfS0165] int  NULL,
                                    [FEntrySelfS0166] int  NULL,
                                    [FEntrySelfS0167] int  NULL,
                                    [FEntrySelfS0168] int  NULL,
                                    [FEntrySelfS0169] int  NULL,
                                    [FEntrySelfS0170] int  NULL,
                                    [FEntrySelfS0171] int  NULL,
                                    [FEntrySelfS0172] int  NULL,
                                    [FEntrySelfS0173] int  NULL,
                                    [FEntrySelfS0174] int  NULL,
                                    [FEntrySelfS0175] int  NULL,
                                    [FEntrySelfS0176] decimal(28,10)  NULL,
                                    [FEntrySelfS0177] decimal(28,10)  NULL,
                                    [FEntrySelfS0178] decimal(28,10)  NULL,
                                    [FEntrySelfS0179] decimal(28,10)  NULL,
                                    [FEntrySelfS0180] decimal(28,10)  NULL,
                                    [FEntrySelfS0181] decimal(28,10)  NULL,
                                    [FEntrySelfS0182] varchar(1000) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FEntrySelfS0183] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FEntrySelfS0184] int  NULL,
                                    [FEntrySelfS0185] int  NULL,
                                    [FEntrySelfS0186] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FEntrySelfS0187] varchar(1000) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FEntrySelfS0189] int  NULL,
                                    [FEntrySelfS0190] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FEntrySelfS0188] datetime  NULL,
                                    [FEntrySelfS0191] varchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
                                    [FEntrySelfS0194] int  NULL,
                                    [FEntrySelfS0195] int  NULL,
                                    [FEntrySelfS0196] int  NULL,
                                    [FEntrySelfS0192] decimal(28,10)  NULL,
                                    [FEntrySelfS0193] decimal(20,2)  NULL,
                                    [FEntrySelfS0197] int  NULL,
                                    [FEntrySelfS0198] int  NULL,
                                    [FEntrySelfS0199] decimal(28,10)  NULL,
                                    [FEntrySelfS01100] decimal(28,10)  NULL,
                                    [FEntrySelfS01101] decimal(28,10)  NULL
)
    ON [PRIMARY]
GO