#%RAML 1.0
title: ym-trace
baseUri: 0.0.0.0:18081
description: YM-TRACE API
version: 1.0


/getProductQualityPlanBySaleOrder:
  description: 根据订单号,查询明细产品及其质量计划
  get:
    queryParameters:
      orderId:
        type: string
        example: 'XSDD2014052086'
    responses:
      '200':
        body:
          application/json:
